# Generated by Django 4.1.3 on 2022-11-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория награды',
                'verbose_name_plural': 'Категории наград',
                'db_table': 'reward__category',
            },
        ),
        migrations.CreateModel(
            name='RewardTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип награды',
                'verbose_name_plural': 'Типы наград',
                'db_table': 'reward__type',
            },
        ),
        migrations.CreateModel(
            name='RewardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название награды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание награды')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reward_photo/', verbose_name='Фото награды')),
                ('categories', models.ManyToManyField(blank=True, to='reward.rewardcategorymodel', verbose_name='Категории награды')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.rewardtypemodel', verbose_name='Тип награды')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'db_table': 'reward__reward',
            },
        ),
    ]
