# Generated by Django 4.1.3 on 2022-11-20 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0002_rewardmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardmodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='rewardmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
