# Generated by Django 4.1.3 on 2022-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('parent', 'Родитель'), ('student', 'Ученик')], default='student', max_length=12, verbose_name='Роль'),
        ),
    ]
